import { describe,it,expect } from 'vitest';
import fc from 'fast-check';
import { createEvent,createPerson,createSampleEvent } from '../src/core/defaults';
import { dateOf,clockOf,toMinute,splitByDay,overlap,dayIntervals } from '../src/core/time';
import { availabilityState,canAssign,validateEvent } from '../src/core/validate';
import { schedule } from '../src/core/scheduler';
import { confirmEvent,newRevision } from '../src/core/revisions';
import { History } from '../src/core/history';
import type { Assignment,EventData,Person } from '../src/core/types';
const date='2026-10-10'; const t=(s:string)=>toMinute(date,s);
function fixture(count=1):EventData {
  const e=createEvent('가상 검증 행사');e.days=[{id:'day',date,start:'09:00',end:'17:00',nextDay:false}];e.locations=[{id:'L',name:'장소'},{id:'M',name:'다른 장소'}];e.roles=[{id:'R',name:'안내',requiredTags:[]},{id:'S',name:'접수',requiredTags:[]}];e.demands=[{id:'D',locationId:'L',roleId:'R',start:t('09:00'),end:t('17:00'),count,leaderTag:'',leaderMin:0,phase:'본행사'}];e.policy.minimumAssignment=30;e.policy.preferredShift=60;e.policy.timeLimitMs=10000;return e;
}
function person(id='A',start='09:00',end='17:00'):Person { const p=createPerson('가상 동일인');p.id=id;p.availability=[{id:`av-${id}`,start:t(start),end:t(end),state:'available'}];return p; }
function a(id:string,p:string,start:string,end:string,locationId='L',roleId='R'):Assignment{return{id,personId:p,start:t(start),end:t(end),locationId,roleId,source:'manual',locked:false};}
const codes=(e:EventData)=>validateEvent(e).errors.map(i=>i.code);
const run=(e:EventData,mode:'all'|'fill'='all')=>schedule(e,{mode,seed:11,timeLimitMs:10000});

describe('정수 분·독립 검증기',()=>{
  it('01 반열린 구간의 중복은 차단하고 맞닿은 배정은 허용한다',()=>{const e=fixture();e.people=[person()];e.assignments=[a('a','A','09:00','10:00'),a('b','A','10:00','11:00')];expect(codes(e)).not.toContain('OVERLAP');e.assignments[1].start=t('09:59');expect(codes(e)).toContain('OVERLAP');expect(overlap({start:0,end:60},{start:60,end:90})).toBe(false);});
  it('02 같은 이름의 서로 다른 ID가 독립 배정된다',()=>{const e=fixture(2);e.demands[0].end=t('10:00');e.people=[person('A'),person('B')];const r=run(e);expect(r.validation.errors).toEqual([]);expect(r.validation.shortageMinutes).toBe(0);expect(new Set(r.assignments.map(a=>a.personId)).size).toBe(2);});
  it('03 넓은 가능시간보다 부분 불가시간이 우선한다',()=>{const e=fixture();const p=person();p.availability.push({id:'lunch',start:t('12:00'),end:t('13:00'),state:'unavailable'});e.people=[p];const r=run(e);expect(r.assignments.every(a=>!overlap(a,{start:t('12:00'),end:t('13:00')}))).toBe(true);expect(r.validation.shortageMinutes).toBe(60);});
  it('04 미확인/선호만으로는 배정하지 않고 명시적 가능 설정을 요구한다',()=>{const e=fixture();const p=person();p.availability=[];e.people=[p];expect(run(e).assignments).toEqual([]);p.availability=[{id:'a',start:t('09:00'),end:t('17:00'),state:'preferred'}];expect(availabilityState(p,t('09:00'),t('10:00'))).toBe('unknown');p.availability[0].state='available';expect(run(e).validation.shortageMinutes).toBe(0);p.availability.push({id:'u',start:t('10:00'),end:t('11:00'),state:'unknown'});expect(availabilityState(p,t('10:00'),t('11:00'))).toBe('unknown');});
  it('05 부족하면 같은 사람을 중복 투입하지 않는다',()=>{const e=fixture(2);e.demands[0].end=t('10:00');e.people=[person()];const r=run(e);expect(r.validation.shortageMinutes).toBe(60);expect(r.validation.shortages.every(s=>s.missing===1)).toBe(true);expect(r.validation.personMinutes.A).toBe(60);});
  it('06 자격과 총 3명 중 책임자 1명을 합산한다',()=>{const e=fixture(3);e.demands[0].end=t('10:00');e.demands[0].leaderTag='책임자';e.demands[0].leaderMin=1;e.roles[0].requiredTags=['안내'];e.people=[person('lead'),person('A'),person('B'),person('unqualified')];e.people.slice(0,3).forEach(p=>p.tags=['안내']);e.people[0].tags.push('책임자');const r=run(e);expect(r.validation.errors).toEqual([]);expect(r.assignments).toHaveLength(3);expect(r.assignments.some(a=>a.personId==='unqualified')).toBe(false);expect(r.validation.coveredMinutes).toBe(180);});
  it('책임자 미충족은 채울 수 있는 집계 조건이며 잘못된 고정배정과 다르다',()=>{const e=fixture(2);e.demands[0].end=t('10:00');e.demands[0].leaderTag='lead';e.demands[0].leaderMin=1;e.people=[person('A'),person('B')];e.people[1].tags=['lead'];e.assignments=[a('fixed','A','09:00','10:00')];e.assignments[0].locked=true;expect(run(e,'fill').status).toBe('complete');expect(run(e,'fill').validation.errors).toEqual([]);});
  it('07 일별·전체 상한과 휴게·이동 조건을 각각 검사한다',()=>{const e=fixture();e.people=[person()];const p=e.people[0];p.maxDaily=60;p.maxTotal=90;p.maxContinuous=60;p.minBreak=30;e.policy.travelMinutes=20;e.assignments=[a('a','A','09:00','10:00'),a('b','A','10:10','11:10','M')];e.demands.push({...e.demands[0],id:'M',locationId:'M'});expect(codes(e)).toEqual(expect.arrayContaining(['MAX_DAILY','MAX_TOTAL','MIN_BREAK','TRAVEL']));});
  it('08 역할 변경도 연속시간에 포함된다',()=>{const e=fixture();e.people=[person()];e.people[0].maxContinuous=60;e.demands.push({...e.demands[0],id:'S',roleId:'S'});e.assignments=[a('a','A','09:00','10:00'),a('b','A','10:00','11:00','L','S')];expect(codes(e)).toContain('MAX_CONTINUOUS');});
  it('09 잠금은 유지하고 충돌한 잠금에서 성공을 보고하지 않는다',()=>{const e=fixture();e.people=[person()];e.assignments=[{...a('a','A','09:00','10:00'),locked:true},{...a('b','A','09:30','10:30'),locked:true}];const before=structuredClone(e);const r=run(e);expect(r.status).toBe('invalid-fixed');expect(r.assignments).toEqual(e.assignments);expect(e).toEqual(before);});
  it('10 빈자리만 모드는 수동배정을 보존한다',()=>{const e=fixture();e.people=[person('A'),person('B')];e.assignments=[a('manual','B','10:00','11:00')];const r=run(e,'fill');expect(r.assignments.find(a=>a.id==='manual')).toEqual(e.assignments[0]);expect(r.validation.errors).toEqual([]);});
  it('10 선택 범위·장소 밖의 배정을 보존한다',()=>{const e=fixture();e.people=[person('A'),person('B')];e.demands.push({...e.demands[0],id:'M',locationId:'M'});e.assignments=[a('wide','A','09:00','12:00'),a('other','B','09:00','12:00','M')];const r=schedule(e,{mode:'selected',range:{start:t('10:00'),end:t('11:00')},locationId:'L',timeLimitMs:10000});expect(r.assignments.find(a=>a.id==='other')).toEqual(e.assignments[1]);expect(r.assignments.find(a=>a.id==='wide')).toMatchObject({start:t('09:00'),end:t('10:00'),personId:'A'});expect(r.assignments.find(a=>a.id.startsWith('wide-after'))).toMatchObject({start:t('11:00'),end:t('12:00'),personId:'A'});expect(r.validation.errors).toEqual([]);});
  it('선택 경계가 밖의 최소 교대를 쪼개면 기존 근무를 안전하게 보존한다',()=>{const e=fixture();e.policy.minimumAssignment=60;e.people=[person('A'),person('B')];e.assignments=[a('wide','A','09:00','11:00')];const r=schedule(e,{mode:'selected',range:{start:t('09:30'),end:t('10:30')}});expect(r.assignments.find(a=>a.id==='wide')).toEqual(e.assignments[0]);expect(r.validation.errors).toEqual([]);expect(r.explanation).toContain('전체를 보존');});
  it('선택 재배정은 범위 밖 각 분의 담당·장소·역할과 비분할 원본 ID 및 잠금을 보존한다',()=>{const e=fixture(2);e.people=[person('A'),person('B'),person('C')];e.assignments=[a('crossing','A','09:00','12:00'),{...a('locked','B','10:00','11:00'),locked:true},a('later','C','14:00','15:00')];const before=structuredClone(e),range={start:t('10:00'),end:t('11:00')};const r=schedule(e,{mode:'selected',range,timeLimitMs:10000});const outside=(jobs:Assignment[])=>{const rows:string[]=[];for(const x of jobs)for(let m=x.start;m<x.end;m++)if(m<range.start||m>=range.end)rows.push([m,x.personId,x.locationId,x.roleId,x.locked,x.source].join('|'));return rows.sort();};expect(outside(r.assignments)).toEqual(outside(before.assignments));expect(r.assignments.find(a=>a.id==='later')).toEqual(before.assignments[2]);expect(r.assignments.find(a=>a.id==='locked')).toEqual(before.assignments[1]);expect(r.assignments.find(a=>a.id==='crossing')).toEqual({...before.assignments[0],end:range.start});expect(r.assignments.find(a=>a.id===`crossing-after-${range.end}`)).toEqual({...before.assignments[0],id:`crossing-after-${range.end}`,start:range.end});expect(e).toEqual(before);expect(r.validation.errors).toEqual([]);});
  it('잘못된 seed·탐색 제한·선택 범위는 원본을 보존하며 거절한다',()=>{const e=fixture();e.people=[person()];for(const options of [{mode:'all' as const,seed:NaN},{mode:'all' as const,seed:-1},{mode:'all' as const,timeLimitMs:NaN},{mode:'selected' as const,range:{start:t('09:00'),end:NaN}}]){const r=schedule(e,options);expect(r.status).toBe('invalid-fixed');expect(r.assignments).toEqual(e.assignments);}});
  it('11 취소와 Undo/Redo가 이전 배정·합계를 복구한다',()=>{const e=fixture();e.people=[person()];const before=structuredClone(e);let ticks=0;const cancelled=schedule(e,{mode:'all',shouldCancel:()=>++ticks>2});expect(cancelled.status).toBe('cancelled');expect(cancelled.assignments).toEqual(before.assignments);expect(e).toEqual(before);const h=new History(e);const next={...e,assignments:run(e).assignments};h.commit(next);expect(validateEvent(h.undo()).personMinutes.A).toBe(0);expect(validateEvent(h.redo()).personMinutes.A).toBe(480);});
  it('12 시간대별 수요의 분모와 부족 인분을 정확히 계산한다',()=>{const e=fixture();e.people=[person()];e.demands=[{...e.demands[0],end:t('10:00'),count:2},{...e.demands[0],id:'later',start:t('10:00'),end:t('10:30'),count:1}];e.assignments=[a('a','A','09:00','10:30')];const v=validateEvent(e);expect(v.requiredMinutes).toBe(150);expect(v.coveredMinutes).toBe(90);expect(v.shortageMinutes).toBe(60);expect(v.locationStats.L).toEqual({requiredMinutes:150,coveredMinutes:90,shortageMinutes:60});});
  it('13 명시적 자정 넘김 60분을 일별 30분으로 분할한다',()=>{const e=fixture();const start=t('23:30'),end=toMinute(date,'00:30',true);e.days=[{id:'day',date,start:'23:30',end:'00:30',nextDay:true}];e.demands=[{...e.demands[0],start,end}];const p=person();p.maxDaily=30;p.availability=[{id:'night',start,end,state:'available'}];e.people=[p];e.assignments=[{...a('a','A','09:00','10:00'),start,end}];const v=validateEvent(e);expect(v.errors).toEqual([]);expect(v.personMinutes.A).toBe(60);expect(v.dailyMinutes.A).toEqual({'2026-10-10':30,'2026-10-11':30});expect(splitByDay(start,end).map(a=>a.minutes)).toEqual([30,30]);expect(run(e).validation.dailyMinutes.A).toEqual({'2026-10-10':30,'2026-10-11':30});expect(clockOf(end)).toBe('00:30');expect(dateOf(end)).toBe('2026-10-11');e.days[0].nextDay=false;expect(codes(e)).toContain('INVALID_DAY');});
  it('14 연락 담당은 점유하지 않고 전담자는 역할·장소와 무관하게 점유한다',()=>{const e=fixture();e.people=[person()];e.assignments=[a('a','A','09:00','10:00')];e.programs=[{id:'p',title:'가상 안내',locationId:'M',personId:'A',start:t('09:00'),end:t('10:00'),dedicated:false,publicNote:'',internalNote:'',allowSharedLocation:false}];expect(validateEvent(e).personMinutes.A).toBe(60);expect(codes(e)).not.toContain('OVERLAP');e.programs[0].dedicated=true;expect(codes(e)).toContain('OVERLAP');expect(validateEvent(e).personMinutes.A).toBe(120);});
  it('전담 진행 구간을 자동배정에서도 피하며 연락 담당은 차단하지 않는다',()=>{const e=fixture();e.demands[0].end=t('11:00');e.people=[person()];e.programs=[{id:'program',title:'가상 개회',start:t('09:00'),end:t('10:00'),personId:'A',locationId:'M',dedicated:true,publicNote:'',internalNote:'',allowSharedLocation:false}];let r=run(e);expect(r.validation.errors).toEqual([]);expect(r.validation.coveredMinutes).toBe(60);expect(r.assignments.every(a=>a.start>=t('10:00'))).toBe(true);e.programs[0].dedicated=false;r=run(e);expect(r.validation.coveredMinutes).toBe(120);});
  it('0명 수요와 운영하지 않는 구간을 채우지 않는다',()=>{const e=fixture();e.people=[person()];e.demands=[{...e.demands[0],end:t('10:00'),count:0},{...e.demands[0],id:'active',start:t('11:00'),end:t('12:00'),count:1}];const r=run(e);expect(r.assignments.every(a=>a.start>=t('11:00')&&a.end<=t('12:00'))).toBe(true);expect(r.validation.requiredMinutes).toBe(60);expect(r.validation.shortageMinutes).toBe(0);expect(canAssign(e,a('zero','A','09:00','10:00')).map(i=>i.code)).toContain('OUTSIDE_DEMAND');});
  it('15 다른 날짜로 복사한 배정의 불가시간을 재검사한다',()=>{const e=fixture();e.days.push({id:'day2',date:'2026-10-11',start:'09:00',end:'17:00',nextDay:false});e.people=[person()];e.people[0].availability.push({id:'day2',start:t('09:00')+1440,end:t('17:00')+1440,state:'unavailable'});e.demands.push({...e.demands[0],id:'d2',start:t('09:00')+1440,end:t('17:00')+1440});const copy={...a('copy','A','09:00','10:00'),start:t('09:00')+1440,end:t('10:00')+1440};expect(canAssign(e,copy).map(i=>i.code)).toContain('UNAVAILABLE');});
  it('16 확정 스냅샷이 이후 이름·행사·배정 변경에서 분리된다',()=>{const e=fixture();e.people=[person()];e.assignments=run(e).assignments;const confirmed=confirmEvent(e),saved=structuredClone(confirmed.snapshots[0].data);const revised=newRevision(confirmed);revised.people[0].name='가상 변경';revised.assignments[0].end-=10;revised.name='행사 변경';expect(revised.snapshots[0].data).toEqual(saved);expect(confirmed.snapshots[0].data).toEqual(saved);expect(revised.edition).toBe(2);});
  it('20 빈 명단·빈 행사·진행표 전용 모드를 처리한다',()=>{const e=createEvent();e.days=[];expect(validateEvent(e).errors).toEqual([]);expect(run(e).assignments).toEqual([]);e.mode='program';e.days=[{id:'day',date,start:'09:00',end:'17:00',nextDay:false}];e.locations=[{id:'L',name:'장소'},{id:'M',name:'다른 곳'}];e.programs=[{id:'p',title:'가상 개회',start:t('09:00'),end:t('10:00'),locationId:'L',personId:'',dedicated:false,allowSharedLocation:false,publicNote:'',internalNote:''},{id:'q',title:'병렬 안내',start:t('09:00'),end:t('10:00'),locationId:'M',personId:'',dedicated:false,allowSharedLocation:false,publicNote:'',internalNote:''}];expect(validateEvent(e).errors).toEqual([]);expect(validateEvent(e).warnings).toEqual([]);e.programs[1].locationId='L';expect(validateEvent(e).warnings[0].code).toBe('PROGRAM_LOCATION_OVERLAP');});
  it('22 동일 데이터·정책·seed의 결과가 같고 시간제한은 불가능이 아니다',()=>{const e=createSampleEvent();const x=run(e),y=run(e);expect(x.assignments).toEqual(y.assignments);expect(x.validation).toEqual(y.validation);const timed=schedule(e,{mode:'all',timeLimitMs:0});expect(timed.status).toBe('timeout');expect(timed.explanation).toContain('불가능하다는 뜻은 아닙니다');});
  it('초기 부족 설명도 가능·불가 경계를 반영하고 교대로 충족할 인원을 0명이라 하지 않는다',()=>{const e=createSampleEvent();const v=validateEvent(e);expect(v.shortages.length).toBeGreaterThan(e.demands.length);expect(v.shortages.every(s=>!s.reason.includes('후보 0명'))).toBe(true);expect(v.shortages.every(s=>!s.reason.includes('책임자가 없습니다'))).toBe(true);const total=e.demands.reduce((n,d)=>n+(d.end-d.start)*d.count,0);expect(v.requiredMinutes).toBe(total);expect(v.shortageMinutes).toBe(total);});
  it('행사·장소·역할의 빈 이름과 중복 운영 날짜는 확정 전에 오류로 보인다',()=>{const e=fixture();e.name=' ';e.locations[0].name='';e.roles[0].name='';e.days.push({...e.days[0],id:'duplicate'});expect(codes(e)).toEqual(expect.arrayContaining(['EMPTY_EVENT_NAME','EMPTY_LOCATION_NAME','EMPTY_ROLE_NAME','DUPLICATE_DATE']));expect(()=>confirmEvent(e)).toThrow();});
  it('외부 ID __proto__/constructor/toString도 사전 프로토타입을 바꾸지 않고 합산한다',()=>{const e=fixture();const ids=['__proto__','constructor','toString'];e.people=ids.map(id=>person(id));e.locations=ids.map(id=>({id,name:'가상 장소 '+id}));e.demands=ids.map((id,i)=>({...e.demands[0],id:'D'+i,locationId:id,end:t('10:00')}));e.assignments=ids.map((id,i)=>a('a'+i,id,'09:00','10:00',id));const v=validateEvent(e);expect(v.errors).toEqual([]);expect(Object.keys(v.personMinutes).sort()).toEqual([...ids].sort());for(const id of ids){expect(v.personMinutes[id]).toBe(60);expect(v.dailyMinutes[id][date]).toBe(60);expect(v.locationStats[id]).toEqual({requiredMinutes:60,coveredMinutes:60,shortageMinutes:0});}expect(v.requiredMinutes).toBe(180);expect(v.coveredMinutes).toBe(180);expect(Object.getPrototypeOf(v.personMinutes)).toBeNull();expect(Object.getPrototypeOf(v.dailyMinutes)).toBeNull();expect(Object.getPrototypeOf(v.locationStats)).toBeNull();expect(Object.hasOwn(Object.prototype,'requiredMinutes')).toBe(false);expect(Object.hasOwn(Object,'requiredMinutes')).toBe(false);});
  it('불연속 눈금 09:07~09:52를 반올림하거나 30분 교대로 자르지 않는다',()=>{const e=fixture();e.policy.minimumAssignment=1;e.policy.preferredShift=120;e.demands[0].start=t('09:07');e.demands[0].end=t('09:52');e.people=[person('A','09:07','09:52')];const r=run(e);expect(r.validation.shortageMinutes).toBe(0);expect(r.assignments).toHaveLength(1);expect(r.assignments[0]).toMatchObject({start:t('09:07'),end:t('09:52')});});
  it('짧은 전역 경계가 교대를 강제하지 않고 최소 배정 60분을 지킨다',()=>{const e=fixture();e.policy.minimumAssignment=60;e.policy.preferredShift=120;e.demands[0].end=t('11:00');e.people=[person('A'),person('B','09:17','09:27')];const r=run(e);expect(r.validation.errors).toEqual([]);expect(r.validation.shortageMinutes).toBe(0);expect(r.assignments.every(a=>a.end-a.start>=60)).toBe(true);});
  it('같은 seed의 빈자리 재실행도 기존 자동 ID와 충돌하지 않는다',()=>{const e=fixture();e.people=[person()];e.assignments=run(e).assignments;e.demands[0].count=2;e.people.push(person('B'));const r=run(e,'fill');expect(r.validation.errors).toEqual([]);expect(new Set(r.assignments.map(a=>a.id)).size).toBe(r.assignments.length);});
  it('필수 최소시간과 희망 최소시간을 분리한다',()=>{const e=fixture();e.people=[person('A'),person('B')];e.people[0].minMinutes=60;e.people[0].minMode='hard';e.people[1].minMinutes=60;const v=validateEvent(e);expect(v.errors.some(i=>i.code==='HARD_MIN')).toBe(true);expect(v.warnings.some(i=>i.code==='SOFT_MIN')).toBe(true);expect(canAssign(e,a('a','A','09:00','09:30')).map(i=>i.code)).not.toContain('HARD_MIN');});
  it('허용한 수동 초과만 경고하며 자동 초과는 항상 오류다',()=>{const e=fixture();e.people=[person('A'),person('B')];e.policy.allowOverstaff=true;e.assignments=[a('a','A','09:00','10:00'),a('b','B','09:00','10:00')];expect(validateEvent(e).warnings.some(i=>i.code==='OVERSTAFF')).toBe(true);expect(codes(e)).not.toContain('OVERSTAFF');e.assignments[0].source='auto';expect(codes(e)).not.toContain('OVERSTAFF');expect(canAssign(e,{...e.assignments[1],source:'auto'}).map(i=>i.code)).toContain('OVERSTAFF');e.assignments[1].source='auto';expect(codes(e)).toContain('OVERSTAFF');});
  it('날짜·시간 유효성을 확인하고 운영시간 미입력을 자동 익일로 해석하지 않는다',()=>{expect(()=>toMinute('2026-02-30','10:00')).toThrow();expect(()=>toMinute(date,'24:00')).toThrow();const e=fixture();e.days[0].end='08:00';expect(codes(e)).toContain('INVALID_DAY');expect(dayIntervals(fixture())[0].start).toBe(t('09:00'));});
});

describe('독립 기준·무작위 성질',()=>{
  it('브루트포스 작은 정답: 가능한 사람 조합을 엔진 없이 전수 비교한다',()=>{
    for(let mask=0;mask<16;mask++) {
      const e=fixture();e.policy.preferredShift=30;e.demands[0].end=t('10:00');e.people=[person('A'),person('B')];
      e.people.forEach((p,pi)=>{p.availability=[];for(let slot=0;slot<2;slot++)if(mask&(1<<(pi*2+slot)))p.availability.push({id:`${pi}-${slot}`,start:t('09:00')+slot*30,end:t('09:00')+(slot+1)*30,state:'available'});});
      let best=0;
      for(const first of [-1,0,1])for(const second of [-1,0,1]) {let score=0,feasible=true;for(const [slot,pi] of [first,second].entries()){if(pi>=0){if(!(mask&(1<<(pi*2+slot))))feasible=false;else score+=30;}}if(feasible)best=Math.max(best,score);}
      const r=run(e);expect(r.validation.coveredMinutes,`mask ${mask}`).toBe(best);expect(r.validation.errors).toEqual([]);
    }
  });
  it('불가로 바뀐 B 때문에 후반 30분이 부족해도 A에게 강제하지 않는다',()=>{const e=fixture();e.demands[0].end=t('10:00');e.people=[person('A','09:00','09:30'),person('B','09:30','10:00')];expect(run(e).validation.coveredMinutes).toBe(60);e.people[1].availability[0].state='unavailable';const r=run(e);expect(r.validation.coveredMinutes).toBe(30);expect(r.validation.shortageMinutes).toBe(30);expect(r.assignments.every(a=>a.personId!=='A'||a.end<=t('09:30'))).toBe(true);});
  it('무작위 100회: 독립 분 단위 오라클로 인원·가능시간·상한·중복을 검사한다',()=>{
    fc.assert(fc.property(fc.array(fc.tuple(fc.integer({min:0,max:5}),fc.integer({min:1,max:6}),fc.integer({min:0,max:120})),{minLength:0,maxLength:6}),fc.integer({min:1,max:3}),fc.integer({min:0,max:100000}), (rows,count,seed)=>{
      const e=fixture(count);e.policy.minimumAssignment=1;e.policy.preferredShift=30;e.demands[0].end=t('12:00');e.people=rows.map(([start,end,max],i)=>{const p=person(`P${i}`);const s=Math.min(start,end-1)*30,stop=Math.max(start+1,end)*30;p.availability=[{id:`a${i}`,start:t('09:00')+s,end:t('09:00')+stop,state:'available'}];p.maxTotal=max;p.maxContinuous=60;p.minBreak=15;return p;});
      const r=schedule(e,{mode:'all',seed,timeLimitMs:10000});expect(r.validation.errors).toEqual([]);
      for(let minute=t('09:00');minute<t('12:00');minute++){const active=r.assignments.filter(a=>a.start<=minute&&a.end>minute);expect(active.length).toBeLessThanOrEqual(count);expect(new Set(active.map(a=>a.personId)).size).toBe(active.length);for(const a of active){const p=e.people.find(p=>p.id===a.personId)!;expect(p.availability.some(av=>av.start<=minute&&av.end>minute)).toBe(true);}}
      for(const p of e.people){const jobs=r.assignments.filter(a=>a.personId===p.id).sort((a,b)=>a.start-b.start);const total=jobs.reduce((n,a)=>n+a.end-a.start,0);expect(total).toBeLessThanOrEqual(p.maxTotal!);let run=0,last=-1;for(const a of jobs){if(a.start===last)run+=a.end-a.start;else{if(last>=0)expect(a.start-last).toBeGreaterThanOrEqual(15);run=a.end-a.start;}expect(run).toBeLessThanOrEqual(60);last=a.end;}}
      expect(r.validation.coveredMinutes+r.validation.shortageMinutes).toBe(r.validation.requiredMinutes);
    }),{numRuns:100,seed:20261010});
  });
});

describe('검증기 독립 분 단위 오라클',()=>{
  it('무작위 기존 배정 100회: 중복·연속시간·일별/전체 합계를 독립 비교한다',()=>{
    fc.assert(fc.property(fc.array(fc.tuple(fc.integer({min:0,max:150}),fc.integer({min:1,max:30}),fc.boolean()),{maxLength:10}),rows=>{
      const e=fixture(10);e.policy.minimumAssignment=1;e.demands.push({...e.demands[0],id:'second-role',roleId:'S'});const p=person();p.maxContinuous=45;p.maxDaily=90;p.maxTotal=120;e.people=[p];e.assignments=rows.map(([start,duration,other],i)=>({...a(`job${i}`,'A','09:00','10:00','L',other?'S':'R'),start:t('09:00')+start,end:t('09:00')+start+duration}));
      const minutes=Array.from({length:180},(_,i)=>e.assignments.filter(a=>a.start<=t('09:00')+i&&a.end>t('09:00')+i).length);let continuous=0,longest=0;for(const n of minutes){continuous=n>0?continuous+1:0;longest=Math.max(longest,continuous);}const total=rows.reduce((sum,row)=>sum+row[1],0);const v=validateEvent(e),set=new Set(v.errors.map(i=>i.code));
      expect(set.has('OVERLAP')).toBe(minutes.some(n=>n>1));expect(set.has('MAX_CONTINUOUS')).toBe(longest>45);expect(set.has('MAX_DAILY')).toBe(total>90);expect(set.has('MAX_TOTAL')).toBe(total>120);expect(v.personMinutes.A).toBe(total);expect(v.dailyMinutes.A[date]??0).toBe(total);
    }),{numRuns:100,seed:20261011});
  });
  it('무작위 역할·책임자·불가·휴게·이동·분 경계 50회에서 하드 위반을 만들지 않는다',()=>{
    fc.assert(fc.property(fc.array(fc.tuple(fc.boolean(),fc.boolean(),fc.integer({min:0,max:90})),{minLength:3,maxLength:7}),fc.integer({min:0,max:10000}),(rows,seed)=>{
      const e=fixture(2);e.policy.minimumAssignment=5;e.policy.preferredShift=37;e.policy.travelMinutes=11;e.demands[0].start=t('09:07');e.demands[0].end=t('12:03');e.demands[0].leaderTag='lead';e.demands[0].leaderMin=1;e.demands.push({...e.demands[0],id:'other',locationId:'M',roleId:'S',leaderMin:0,count:1});e.roles[1].requiredTags=['special'];
      e.people=rows.map(([lead,special,lunch],i)=>{const p=person(`p${i}`);p.tags=[...(lead?['lead']:[]),...(special?['special']:[])];p.maxDaily=117;p.maxTotal=150;p.maxContinuous=53;p.minBreak=7;p.availability.push({id:`off${i}`,start:t('10:00')+lunch,end:t('10:00')+lunch+13,state:'unavailable'});return p;});
      const r=schedule(e,{mode:'all',seed,timeLimitMs:10000});expect(r.validation.errors.filter(i=>i.code!=='LEADER_SHORTAGE')).toEqual([]);
      for(const p of e.people){const jobs=r.assignments.filter(a=>a.personId===p.id).sort((a,b)=>a.start-b.start);expect(jobs.reduce((s,a)=>s+a.end-a.start,0)).toBeLessThanOrEqual(117);let run=0;for(let i=0;i<jobs.length;i++){const x=jobs[i],prev=jobs[i-1];expect(x.end-x.start).toBeGreaterThanOrEqual(5);for(let m=x.start;m<x.end;m++){expect(p.availability.some(a=>a.state==='available'&&a.start<=m&&a.end>m)).toBe(true);expect(p.availability.some(a=>a.state==='unavailable'&&a.start<=m&&a.end>m)).toBe(false);}if(x.roleId==='S')expect(p.tags).toContain('special');if(prev){expect(x.start).toBeGreaterThanOrEqual(prev.end);if(x.start>prev.end)expect(x.start-prev.end).toBeGreaterThanOrEqual(7);if(x.locationId!==prev.locationId)expect(x.start-prev.end).toBeGreaterThanOrEqual(11);}run=prev&&prev.end===x.start?run+x.end-x.start:x.end-x.start;expect(run).toBeLessThanOrEqual(53);}}
      for(let m=t('09:07');m<t('12:03');m++)for(const d of e.demands){const present=r.assignments.filter(a=>a.locationId===d.locationId&&a.roleId===d.roleId&&a.start<=m&&a.end>m);expect(present.length).toBeLessThanOrEqual(d.count);if(present.length===d.count&&d.leaderMin)expect(present.some(a=>e.people.find(p=>p.id===a.personId)!.tags.includes('lead'))).toBe(true);}
    }),{numRuns:50,seed:20261012});
  });
});
