import Issues from './Issues';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Assignment, EventData, Shortage, ScheduleResult, UpdateEvent } from '../core/types';
import { clockOf, dateOf, dayIntervals, formatRange, toMinute } from '../core/time';
import { canAssign, validateEvent } from '../core/validate';
import { id } from '../core/defaults';
import { assignmentChanges } from '../core/revisions';

type Props={event:EventData;onChange:UpdateEvent;readOnly?:boolean;onNavigate:(step:number,personId?:string)=>void;initialSlot?:Shortage|null};
const personLabel=(e:EventData,id:string)=>{const p=e.people.find(x=>x.id===id);return p?`${p.alias||p.name}${p.team?' · '+p.team:''}`:'삭제된 참여자';};
export default function Board({event:e,onChange,readOnly=false,onNavigate,initialSlot}:Props){
 const [date,setDate]=useState(e.days[0]?.date||'');
 const [editDate,setEditDate]=useState(e.days[0]?.date||'');
 const [view,setView]=useState<'full'|'person'>('full');
 const [location,setLocation]=useState(''); const [team,setTeam]=useState(''); const [personFilter,setPersonFilter]=useState('');
 const [start,setStart]=useState(e.days[0]?.start||'09:00'),[end,setEnd]=useState(e.days[0]?.end||'10:00'),[nextDay,setNextDay]=useState(false);
 const [loc,setLoc]=useState(e.locations[0]?.id||''),[role,setRole]=useState(e.roles[0]?.id||''),[person,setPerson]=useState(''),[editing,setEditing]=useState('');
 const [notice,setNotice]=useState(''),[mode,setMode]=useState<'fill'|'selected'|'all'>('fill');
 const [busy,setBusy]=useState(false),[result,setResult]=useState<ScheduleResult|null>(null),[source,setSource]=useState('');
 const [seed,setSeed]=useState(e.policy.seed),[copyDate,setCopyDate]=useState(e.days[1]?.date||e.days[0]?.date||'');
 const [swapId,setSwapId]=useState('');
 const [editorOpen,setEditorOpen]=useState(false);
 const editorRef=useRef<HTMLElement|null>(null),tableRef=useRef<HTMLElement|null>(null);
 const revealEditor=()=>{setEditorOpen(true);requestAnimationFrame(()=>{if(!window.matchMedia('(max-width: 700px)').matches)editorRef.current?.scrollIntoView({behavior:'smooth',block:'center'});});};
 const showSlot=(s:{start:number;end:number;locationId:string;roleId:string})=>{setDate(dayIntervals(e).find(d=>s.start>=d.start&&s.start<d.end)?.date||dateOf(s.start));setEditDate(dateOf(s.start));setStart(clockOf(s.start));setEnd(clockOf(s.end));setNextDay(dateOf(s.start)!==dateOf(s.end));setLoc(s.locationId);setRole(s.roleId);setLocation('');setView('full');setTeam('');setPersonFilter('');setEditing('');setPerson('');setNotice(`${dateOf(s.start)} ${formatRange(s.start,s.end)} 시간·장소를 선택했습니다.`);revealEditor();};
 useEffect(()=>{if(initialSlot)showSlot(initialSlot)},[initialSlot]);
 const worker=useRef<Worker|null>(null);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const validation=useMemo(()=>validateEvent(e),[e]);
 const day=(()=>{try{return dayIntervals(e).find(d=>d.date===date)}catch{return undefined}})();
 const boundaries=useMemo(()=>{if(!day)return[];const s=new Set([day.start,day.end]);for(let t=day.start;t<day.end;t+=e.policy.gridMinutes)s.add(t);for(const a of [...e.demands,...e.assignments])for(const t of [a.start,a.end])if(t>day.start&&t<day.end)s.add(t);return[...s].sort((a,b)=>a-b)},[day?.start,day?.end,e.policy.gridMinutes,e.demands,e.assignments]);
 const lanes=e.locations.filter(l=>!location||location===l.id).flatMap(l=>e.roles.filter(r=>e.demands.some(d=>d.locationId===l.id&&d.roleId===r.id)||e.assignments.some(a=>a.locationId===l.id&&a.roleId===r.id)).map(r=>({location:l,role:r})));
 const people=e.people.filter(p=>(!team||p.team===team)&&(!personFilter||p.id===personFilter));
 const candidate=useMemo(()=>{try{return {id:editing||'candidate',personId:person,locationId:loc,roleId:role,start:toMinute(editDate,start),end:toMinute(editDate,end,nextDay),locked:false,source:'manual'} as Assignment;}catch{return null}},[editing,person,loc,role,editDate,start,end,nextDay]);
 const base=e.assignments.filter(a=>a.id!==editing);
 const candidates=e.people.map(p=>({p,issues:candidate?canAssign(e,{...candidate,personId:p.id},base).filter(i=>i.severity==='error'):[{message:'시간을 확인하세요.'}]}));
 const select=(a:Assignment)=>{setEditing(a.id);setDate(dayIntervals(e).find(d=>a.start>=d.start&&a.start<d.end)?.date||dateOf(a.start));setEditDate(dateOf(a.start));setStart(clockOf(a.start));setEnd(clockOf(a.end));setNextDay(dateOf(a.end)!==dateOf(a.start));setLoc(a.locationId);setRole(a.roleId);setPerson(a.personId);setNotice('선택한 배정을 수정 패널에서 확인하세요.');revealEditor();};
 const checkApply=(assignments:Assignment[],label:string)=>{
  const before=validateEvent(e).errors,after=validateEvent(e,assignments).errors;
  const existing=new Set(before.map(v=>v.code+'|'+v.personId+'|'+v.message));
  const added=after.filter(v=>!existing.has(v.code+'|'+v.personId+'|'+v.message));
  if(added.length){setNotice('적용하지 않았습니다: '+added.map(v=>v.message).join(' / '));return false;}
  onChange({...e,assignments},label);setNotice(label+' 적용 완료');return true;
 };
 const manual=()=>{
  if(!candidate||!person){setNotice('시간과 참여자를 선택하세요.');return;}
  const old=e.assignments.find(a=>a.id===editing);if(old?.locked){setNotice('먼저 배정 잠금을 해제하세요.');return;}
  const issues=canAssign(e,candidate,base).filter(i=>i.severity==='error');if(issues.length){setNotice(issues.map(v=>v.message).join(' / '));return;}
  // Supervisor gaps can be resolved incrementally, but remain blocking validation errors until complete.
  onChange({...e,assignments:[...base,{...candidate,id:editing||id()}]},editing?'수동 배정 수정':'수동 배정');setEditing('');setEditorOpen(false);setNotice('배정했습니다. 아래 검사 결과를 확인하세요.');
 };
 const run=(nextSeed=seed)=>{
  if(busy)return;
  let range;try{range=mode==='selected'?{start:toMinute(editDate,start),end:toMinute(editDate,end,nextDay)}:undefined;}catch{setNotice('선택 범위 시간을 확인하세요.');return;}
  if(range&&range.end<=range.start){setNotice('종료 시간은 시작보다 늦어야 합니다.');return;}
  setResult(null);setBusy(true);setNotice('조건을 지키는 초안을 계산하고 있습니다. 취소해도 현재 표는 유지됩니다.');setSource(JSON.stringify(e));
  worker.current=new Worker(new URL('../core/scheduler.worker.ts',import.meta.url),{type:'module'});
  worker.current.onmessage=msg=>{setBusy(false);worker.current?.terminate();worker.current=null;if(msg.data.error){setNotice(String(msg.data.error));return;}setResult(msg.data);setNotice('변경 미리보기를 확인한 뒤 적용하세요.');};
  worker.current.onerror=err=>{setBusy(false);worker.current?.terminate();worker.current=null;setNotice('배정 계산 오류: '+err.message);};
  worker.current.postMessage({event:e,options:{mode,range,locationId:location||undefined,seed:nextSeed,timeLimitMs:e.policy.timeLimitMs}});
 };
 const changes=result?assignmentChanges(e.assignments,result.assignments):null;
 const rangeAssignments=()=>candidate?e.assignments.filter(a=>a.start<candidate.end&&candidate.start<a.end&&(!location||a.locationId===location)):[];
 const clearRange=()=>{const targets=rangeAssignments().filter(a=>!a.locked);if(!targets.length){setNotice('선택 범위에 지울 수 있는 배정이 없습니다.');return;}if(!window.confirm(`${targets.length}건 중 선택 시간과 겹치는 부분만 비웁니다. 잠금은 보존합니다.`))return;
  const targetIds=new Set(targets.map(a=>a.id));const assignments=e.assignments.flatMap(a=>{if(!targetIds.has(a.id)||!candidate)return[a];return [{...a,end:Math.min(a.end,candidate.start)},{...a,id:id(),start:Math.max(a.start,candidate.end)}].filter(x=>x.end>x.start)});checkApply(assignments,'선택 범위 비우기');};
 const copyRange=()=>{if(!candidate)return;let shift;try{shift=toMinute(copyDate,'00:00')-toMinute(editDate,'00:00')}catch{return;}if(!shift){setNotice('다른 대상 날짜를 선택하세요.');return;}const targets=rangeAssignments();const copied=targets.map(a=>({...a,id:id(),start:Math.max(a.start,candidate.start)+shift,end:Math.min(a.end,candidate.end)+shift,locked:false}));if(window.confirm(`${copied.length}건을 ${copyDate}에 복사합니다. 대상 날짜 조건으로 다시 검사합니다.`))checkApply([...e.assignments,...copied],'다른 날짜 배치 복사');};
 const swap=()=>{const a=e.assignments.find(a=>a.id===editing),b=e.assignments.find(a=>a.id===swapId);if(!a||!b||a.id===b.id||a.locked||b.locked){setNotice('서로 다른 잠금 해제 배정 두 건을 선택하세요.');return;}if(window.confirm(`${personLabel(e,a.personId)} ↔ ${personLabel(e,b.personId)} 담당자를 교환하고 다시 검사합니다.`))checkApply(e.assignments.map(x=>x.id===a.id?{...x,personId:b.personId}:x.id===b.id?{...x,personId:a.personId}:x),'담당자 교환');};
 const renderChip=(a:Assignment)=><button key={a.id} type="button" className={'assignment '+(editing===a.id?'selected':'')} style={{borderLeftColor:e.people.find(p=>p.id===a.personId)?.color||'#355c50'}} draggable={!readOnly&&!a.locked} onDragStart={ev=>ev.dataTransfer.setData('text/plain',a.id)} onClick={()=>select(a)} title={formatRange(a.start,a.end)}>{a.locked?'🔒 ':''}{personLabel(e,a.personId)}</button>;
 return <div className="stack">
  <section className="panel"><div className="section-head"><div><p className="eyebrow">04 / 인력 배치</p><h2>빈자리를 채우고, 한 번 더 확인하세요.</h2></div><span className="pill">{e.assignments.length}개 배정</span></div>
   <div className="metrics"><div><strong>{validation.requiredMinutes?Math.round(validation.coveredMinutes/validation.requiredMinutes*100):100}%</strong><span>필요 인원 충족</span></div><div><strong>{validation.shortageMinutes.toLocaleString()}</strong><span>부족 인분</span></div><div><strong>{validation.shortages.filter(s=>s.missing||s.leaderMissing).length}</strong><span>부족 구간</span></div><div><strong>{e.people.filter(p=>!validation.personMinutes[p.id]).length}</strong><span>배정 없는 참여자</span></div></div>
   <div className="toolbar"><label>날짜<select aria-label="배치표 날짜" value={date} onChange={x=>{setDate(x.target.value);setEditDate(x.target.value)}}>{e.days.map(d=><option key={d.id}>{d.date}</option>)}</select></label><label>보기<select value={view} onChange={x=>setView(x.target.value as typeof view)}><option value="full">전체 · 시간 × 장소</option><option value="person">개인별 · 사람 × 시간</option></select></label><label>장소<select value={location} onChange={x=>setLocation(x.target.value)}><option value="">모든 장소</option>{e.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>팀<select value={team} onChange={x=>setTeam(x.target.value)}><option value="">모든 팀</option>{[...new Set(e.people.map(p=>p.team))].filter(Boolean).map(t=><option key={t}>{t}</option>)}</select></label><label>참여자<select value={personFilter} onChange={x=>setPersonFilter(x.target.value)}><option value="">전체</option>{e.people.map(p=><option key={p.id} value={p.id}>{personLabel(e,p.id)}</option>)}</select></label></div>
   {!readOnly&&<div className="auto-bar"><label>배정 범위<select aria-label="자동배정 범위" value={mode} onChange={x=>setMode(x.target.value as typeof mode)}><option value="fill">빈자리만 채우기</option><option value="selected">선택 시간·장소 재배정</option><option value="all">잠금 제외 전체 재배정</option></select></label><label>초안 번호<input aria-label="초안 seed" type="number" min="0" max="4294967295" value={seed} onChange={x=>setSeed(Math.min(4294967295,Math.max(0,Math.trunc(Number(x.target.value)))))}/></label><button className="button primary" disabled={busy} onClick={()=>run()}>자동배정 초안 만들기</button><button className="button secondary" disabled={busy} onClick={()=>{setSeed((seed+1)>>>0);run((seed+1)>>>0)}}>다른 초안</button>{busy&&<button className="button danger" onClick={()=>{worker.current?.terminate();worker.current=null;setBusy(false);setNotice('계산을 취소했습니다. 기존 배치표는 변경되지 않았습니다.')}}>계산 취소</button>}</div>}
   {notice&&<p className="notice" role="status">{notice}</p>}
   {result&&changes&&<div className="preview-box"><h3>배정 변경 미리보기</h3><p className="notice"><strong>아직 적용되지 않은 제안입니다.</strong> 아래 배치표는 현재 저장할 작업본입니다. 검토 후 ‘이 초안 적용’을 누르세요.</p><p>기존 유지 {e.assignments.length-changes.removed.length}건 · 추가 {changes.added.length}건 · 제거 {changes.removed.length}건 · {Math.round(result.elapsedMs)}ms · 초안 {result.seed}</p><p>가능시간·자격·근무조건을 확인한 제안입니다. 남은 부족과 변경 내용을 검토하세요.</p><details><summary>계산 방식 자세히</summary><p>{result.explanation}</p></details><p>검사 오류 {result.validation.errors.length}건 · 부족 {result.validation.shortageMinutes}인분 · {{complete:'빈자리 없이 계산 완료',partial:'일부 빈자리가 남았습니다',timeout:'계산 시간 종료 · 현재 제안 확인',cancelled:'계산 취소', 'invalid-fixed':'유지할 배정의 오류를 먼저 수정하세요'}[result.status]}</p><details><summary>바뀌는 배정 보기</summary><ul>{changes.removed.slice(0,100).map(a=><li key={'r'+a.id}>제거: {personLabel(e,a.personId)} {formatRange(a.start,a.end)}</li>)}{changes.added.slice(0,100).map(a=><li key={'a'+a.id}>추가: {personLabel(e,a.personId)} {formatRange(a.start,a.end)}</li>)}</ul></details><div className="toolbar"><button className="button primary" disabled={readOnly||result.status==='cancelled'||result.status==='invalid-fixed'||source!==JSON.stringify(e)} onClick={()=>{const verified=validateEvent(e,result.assignments);if(verified.errors.some(x=>!['LEADER_SHORTAGE','HARD_MIN'].includes(x.code))){setNotice('독립 검증에서 오류가 있어 적용하지 않았습니다.');return;}onChange({...e,assignments:result.assignments,policy:{...e.policy,seed:result.seed}},'자동배정 적용');setResult(null);setNotice('초안을 적용했습니다. 부족·주의 사항을 확인하세요.')}}>이 초안 적용</button><button className="button secondary" onClick={()=>setResult(null)}>미리보기 닫기</button></div>{source!==JSON.stringify(e)&&<p>입력이 바뀌었습니다. 다시 계산하세요.</p>}</div>}
  </section>
  <section className="panel" ref={tableRef}><div className="section-head"><h3>{date} 배치표</h3><span className="muted small">칸을 눌러 편집 · 🔒 잠금 · 빈자리 숫자는 부족 인원</span></div>
   {!day||!lanes.length?<div className="empty">장소·역할·필요 인원을 먼저 설정하세요.</div>:<div className="table-wrap schedule-wrap"><table className="schedule"><thead><tr><th scope="col">{view==='full'?'시간':'참여자'}</th>{view==='full'?lanes.map(l=><th scope="col" key={l.location.id+l.role.id}>{l.location.name}<small>{l.role.name}</small></th>):boundaries.slice(0,-1).map(t=><th scope="col" key={t}>{clockOf(t)}{dateOf(t)!==date?' +1일':''}</th>)}</tr></thead><tbody>
    {view==='full'?boundaries.slice(0,-1).map((t,i)=><tr key={t}><th scope="row">{clockOf(t)}–{clockOf(boundaries[i+1])}{dateOf(t)!==date?' +1일':''}</th>{lanes.map(l=>{const ds=e.demands.filter(d=>d.locationId===l.location.id&&d.roleId===l.role.id&&d.start<=t&&d.end>=boundaries[i+1]);const needed=ds.reduce((n,d)=>n+d.count,0);const all=e.assignments.filter(a=>a.locationId===l.location.id&&a.roleId===l.role.id&&a.start<boundaries[i+1]&&a.end>t);const as=all.filter(a=>people.some(p=>p.id===a.personId));return <td className={candidate&&candidate.start<boundaries[i+1]&&candidate.end>t&&loc===l.location.id&&role===l.role.id?'focused-slot':undefined} key={l.location.id+l.role.id} onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.preventDefault();if(readOnly)return;const a=e.assignments.find(v=>v.id===ev.dataTransfer.getData('text/plain'));if(!a||a.locked)return;select({...a,start:t,end:t+(a.end-a.start),locationId:l.location.id,roleId:l.role.id});setNotice('이동 위치가 폼에 반영되었습니다. 수동 배정 적용을 눌러 검사 후 이동하세요.');}}>{as.map(renderChip)}<button disabled={readOnly} className={'slot '+(!ds.length?'off':needed===0?'zero':all.length<needed?'short':'filled')} onClick={()=>{setEditing('');setEditDate(dateOf(t));setStart(clockOf(t));setEnd(clockOf(boundaries[i+1]));setNextDay(dateOf(boundaries[i+1])!==dateOf(t));setLoc(l.location.id);setRole(l.role.id);setPerson('');revealEditor();}}>{!ds.length?'운영 없음':needed===0?'필요 0명':all.length<needed?`+ ${needed-all.length}명 빈자리`:`${all.length}/${needed}명 충족`}</button></td>})}</tr>):people.map(p=><tr key={p.id}><th scope="row">{personLabel(e,p.id)}<small>{validation.personMinutes[p.id]||0}분</small></th>{boundaries.slice(0,-1).map((t,i)=><td key={t}>{e.assignments.filter(a=>a.personId===p.id&&a.start<boundaries[i+1]&&a.end>t&&(!location||a.locationId===location)).map(a=><button key={a.id} className="assignment" onClick={()=>select(a)}>{a.locked?'🔒 ':''}{e.locations.find(l=>l.id===a.locationId)?.name} · {e.roles.find(r=>r.id===a.roleId)?.name}</button>)}</td>)}</tr>)}
   </tbody></table></div>}
  </section>
  {!readOnly&&<section ref={editorRef} className={'panel assignment-editor '+(editorOpen?'editor-open':'')} aria-label="선택 배정 편집"><div className="section-head"><h3>선택 범위 · 수동 배정</h3><button className="button secondary mobile-editor-close" onClick={()=>setEditorOpen(false)}>편집 패널 닫기</button></div><p className="editor-context"><strong>{editDate} {start}–{end}{nextDay?' (+1일)':''}</strong> · {e.locations.find(l=>l.id===loc)?.name} / {e.roles.find(r=>r.id===role)?.name}{editing?' · '+personLabel(e,e.assignments.find(a=>a.id===editing)?.personId||''):''}</p><p className="muted">표 눈금과 관계없이 정확한 분을 입력할 수 있습니다. 미확인·불가 시간은 참여자 화면에서 먼저 확인하세요.</p><div className="form-grid"><label>배정 날짜<input type="date" value={editDate} onChange={x=>setEditDate(x.target.value)}/></label><label>시작<input type="time" value={start} onChange={x=>setStart(x.target.value)}/></label><label>종료<input type="time" value={end} onChange={x=>setEnd(x.target.value)}/></label><label className="check"><input type="checkbox" checked={nextDay} onChange={x=>setNextDay(x.target.checked)}/>다음 날 종료 (+1일)</label><label>배정 장소<select value={loc} onChange={x=>setLoc(x.target.value)}><option value="">선택</option>{e.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>배정 역할<select value={role} onChange={x=>setRole(x.target.value)}><option value="">선택</option>{e.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>배정 참여자<select value={person} onChange={x=>setPerson(x.target.value)}><option value="">후보 선택</option>{candidates.map(({p,issues})=><option key={p.id} value={p.id} disabled={issues.length>0}>{personLabel(e,p.id)}{issues.length?' — '+issues[0].message:' · 가능'}</option>)}</select></label></div><div className="toolbar"><button className="button primary" onClick={manual}>수동 배정 적용</button>{editing&&<><button className="button secondary" onClick={()=>{onChange({...e,assignments:e.assignments.map(a=>a.id===editing?{...a,locked:!a.locked}:a)},'배정 잠금 변경')}}>{e.assignments.find(a=>a.id===editing)?.locked?'잠금 해제':'배정 잠금'}</button><button className="button danger" disabled={e.assignments.find(a=>a.id===editing)?.locked} onClick={()=>{onChange({...e,assignments:base},'배정 해제');setEditing('');setEditorOpen(false)}}>배정 해제</button><button className="button secondary" onClick={()=>setEditing('')}>새 배정으로 전환</button></>}</div>
   <details><summary>여러 배정 일괄 조정</summary><p>위 날짜·시작·종료와 상단 장소 필터가 선택 범위입니다. 잠금은 유지합니다.</p><div className="toolbar"><button className="button danger" onClick={clearRange}>선택 범위 비우기</button><label>복사할 날짜<select value={copyDate} onChange={x=>setCopyDate(x.target.value)}>{e.days.map(d=><option key={d.id}>{d.date}</option>)}</select></label><button className="button secondary" onClick={copyRange}>선택 범위 다른 날짜로 복사</button></div><div className="toolbar"><label>교환할 다른 배정<select value={swapId} onChange={x=>setSwapId(x.target.value)}><option value="">선택</option>{e.assignments.filter(a=>a.id!==editing&&!a.locked).map(a=><option key={a.id} value={a.id}>{personLabel(e,a.personId)} {formatRange(a.start,a.end)}</option>)}</select></label><button className="button secondary" disabled={!editing} onClick={swap}>두 사람 교환</button></div></details>
  </section>}
  {(validation.errors.length>0||validation.shortages.length>0)&&<Issues event={e} validation={validation} onSlot={showSlot} onNavigate={onNavigate}/>}
 </div>;
}
