import { useEffect, useState } from 'react';
import { applyConditions, conditionLabels, planConditions, type ConditionKey, type ConditionValues } from '../core/bulkConditions';
import type { EventData, UpdateEvent } from '../core/types';
export default function BulkConditions({event,ids,onChange,readOnly}:{event:EventData;ids:string[];onChange:UpdateEvent;readOnly:boolean}) {
 const [values,setValues]=useState<Record<ConditionKey,string>>({maxDaily:'',maxTotal:'',maxContinuous:'',minBreak:''});
 const [overwrite,setOverwrite]=useState(false),[review,setReview]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>setReview(false),[event,ids.join('|'),values,overwrite]);
 const numbers:ConditionValues={};let error='';
 for(const key of Object.keys(values) as ConditionKey[])if(values[key]!==''){const value=Number(values[key]);if(!Number.isSafeInteger(value)||value<0)error='0 이상의 정수 분을 입력하세요.';else numbers[key]=value;}
 const plan=planConditions(event,ids,numbers,overwrite);
 return <details className="bulk-conditions"><summary>선택한 {ids.length}명 공통 근무조건 설정</summary><p>명단의 체크박스로 대상을 선택하세요. 빈칸은 변경하지 않습니다. 기본값은 기존 개인별 조건 유지입니다.</p><fieldset disabled={readOnly}><div className="form-grid">{(Object.keys(values) as ConditionKey[]).map(key=><label key={key}>공통 {conditionLabels[key]} (분)<input type="number" min="0" step="1" placeholder="변경 안 함" value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</div><label>기존 개인별 조건 처리<select value={overwrite?'overwrite':'keep'} onChange={e=>setOverwrite(e.target.value==='overwrite')}><option value="keep">기존 값 유지 · 비어 있는 조건만 설정</option><option value="overwrite">입력한 항목을 기존 값에도 적용</option></select></label>{error&&<p role="alert">{error}</p>}<button className="button secondary" disabled={!ids.length||!plan.changes.length||!!error} onClick={()=>setReview(true)}>적용 전 변경 내용 확인</button>{review&&<div className="notice"><h4>공통 조건 적용 검토</h4><p>선택 {plan.people.length}명 · 변경 {plan.changes.length}개 조건 · 유지 {plan.kept.length}개 조건</p><p>적용 대상: {plan.people.map(p=>p.name).join(', ')}</p><div className="bulk-preview table-wrap"><table><thead><tr><th>사람</th><th>조건</th><th>기존 → 적용</th></tr></thead><tbody>{plan.changes.map(c=><tr key={c.id+c.key}><td>{c.name}</td><td>{conditionLabels[c.key]}</td><td>{c.before===undefined?'제한 없음':`${c.before}분`} → {c.after}분</td></tr>)}</tbody></table></div><p>기존 배정은 지우지 않습니다. 바뀐 조건과 충돌하면 배치표에서 수정 필요로 표시됩니다. 상단 되돌리기로 한 번에 취소할 수 있습니다.</p><button className="button primary" onClick={()=>{onChange(applyConditions(event,ids,numbers,overwrite),'공통 근무조건 적용');setReview(false);setNotice(`${plan.people.length}명 중 ${new Set(plan.changes.map(c=>c.id)).size}명의 조건을 변경했습니다.`)}}>검토한 공통 조건 적용</button></div>}</fieldset>{notice&&<p role="status">{notice}</p>}</details>;
}
