import { useMemo, useState } from 'react';
import type { EventData, UpdateEvent } from '../core/types';
import { IMPORT_FIELDS, FIELD_LABELS, parseDelimited, readImportFile, previewImport, applyImport, createTemplate, createCsvTemplate, guessMapping, analyzeImportImpact } from '../io/imports';
import type { ImportTable, ColumnMapping } from '../io/imports';
import { downloadBlob } from '../io/exports';
type Kind='roster'|'availability'|'demand';
export default function ImportPanel({event,onChange,readOnly=false}:{event:EventData;onChange:UpdateEvent;readOnly?:boolean}){
 const [kind,setKind]=useState<Kind>('roster'),[mode,setMode]=useState<'append'|'update'|'replace'>('append'),[paste,setPaste]=useState(''),[table,setTable]=useState<ImportTable|null>(null),[mapping,setMapping]=useState<ColumnMapping>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const preview=useMemo(()=>table?previewImport(event,kind,table,mapping):null,[event,kind,table,mapping]);
 const impact=useMemo(()=>preview?analyzeImportImpact(event,preview,mode):null,[event,preview,mode]);
 const load=(t:ImportTable)=>{setTable(t);setMapping(guessMapping(kind,t.headers));setError('');};
 return <section className="panel"><details><summary>CSV / Excel 가져오기 · 입력 서식</summary><p>파일은 이 브라우저에서 처리합니다. 열과 오류를 확인한 뒤 적용하세요. 업로드만으로 기존 자료를 바꾸지 않습니다.</p><div className="toolbar"><label>입력 자료<select value={kind} onChange={x=>{setKind(x.target.value as Kind);setTable(null)}}><option value="roster">참여자 명단</option><option value="availability">참여 가능시간</option><option value="demand">장소별 필요 인원</option></select></label><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{downloadBlob(await createTemplate(kind,event),`${kind}-입력서식.xlsx`)}catch(x){setError(String(x))}finally{setBusy(false)}}}>XLSX 입력 서식 받기</button><button className="button secondary" onClick={()=>downloadBlob(createCsvTemplate(kind),`${kind}-입력서식.csv`)}>CSV 입력 서식 받기</button><label>CSV / XLSX 파일<input type="file" accept=".csv,.tsv,.xlsx" disabled={readOnly} onChange={async x=>{const f=x.target.files?.[0];if(!f)return;setBusy(true);try{load(await readImportFile(f))}catch(err){setError(String(err))}finally{setBusy(false);x.target.value=''}}}/></label></div><label>엑셀 표 붙여넣기 (첫 행은 열 제목)<textarea rows={4} disabled={readOnly} value={paste} onChange={x=>setPaste(x.target.value)} placeholder={'이름\t소속\n가상 참여자\t운영팀'}/></label><button className="button secondary" disabled={!paste||readOnly} onClick={()=>{try{load(parseDelimited(paste))}catch(x){setError(String(x))}}}>붙여넣기 미리보기</button>
 {error&&<p role="alert" className="notice error-text">{error}</p>}
 {table&&preview&&<div className="stack"><h3>열 매핑 · {table.rows.length}행</h3><div className="form-grid">{IMPORT_FIELDS[kind].map(field=><label key={field}>{FIELD_LABELS[field]||field}<select value={mapping[field]??''} onChange={x=>setMapping({...mapping,[field]:x.target.value})}><option value="">연결 안 함</option>{table.headers.map((h,i)=><option key={i} value={h}>{h}</option>)}</select></label>)}</div><div className="table-wrap"><table><thead><tr>{table.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{table.rows.slice(0,8).map((row,i)=><tr key={i}>{row.map((c,j)=><td key={j}>{String(c??'')}</td>)}</tr>)}</tbody></table></div><label>적용 방식<select value={mode} onChange={x=>setMode(x.target.value as typeof mode)}><option value="append">기존 자료에 추가</option><option value="update">기존 ID 기준 업데이트</option><option value="replace">해당 자료 전체 교체</option></select></label>{preview.errors.length>0?<ul className="issue-list error-text">{preview.errors.slice(0,50).map((v,i)=><li key={i}>{v.row}행: {v.message}</li>)}</ul>:<p>입력 오류 없음 · {preview.records.length}개 항목</p>}{impact&&<div className="notice">{impact.messages.map((m,i)=><p key={i}>{m}</p>)}<p>영향받는 기존 배정 {impact.affectedAssignmentIds.length}건</p></div>}<button className="button primary" disabled={readOnly||preview.errors.length>0||!preview.records.length} onClick={()=>{try{if(mode==='replace'&&!window.confirm('표시된 영향을 확인했나요? 이 자료 전체를 교체합니다. 기존 배정에 오류가 생기면 수정 목록으로 표시됩니다.'))return;const applied=applyImport(event,preview,mode);onChange(applied.event,'파일 자료 가져오기');setError('적용했습니다. 배치표의 수정 필요 목록을 확인하세요.');setTable(null);setPaste('')}catch(x){setError(String(x))}}}>미리보기 내용 적용</button></div>}
 </details></section>;
}
